/** French + English stop words for keyword extraction filtering. */
export const STOP_WORDS = new Set([
  // French
  'les', 'des', 'une', 'pour', 'dans', 'avec', 'sur', 'par', 'est', 'sont', 'qui', 'que',
  'vous', 'nous', 'être', 'avoir', 'tout', 'plus', 'très', 'votre', 'notre',
  'aux', 'son', 'ses', 'ces', 'pas', 'mais', 'aussi', 'bien', 'elle', 'elles',
  'ils', 'leur', 'leurs', 'lui', 'mes', 'mon', 'ton', 'tes', 'vos', 'nos',
  'donc', 'car', 'soit', 'dont', 'comme', 'même', 'entre', 'après', 'avant',
  'chez', 'sans', 'sous', 'vers', 'depuis', 'lors', 'dès', 'hors',
  'cette', 'cet', 'ceux', 'celle', 'celles', 'chaque', 'quel', 'quelle',
  'quels', 'quelles', 'quelque', 'quelques', 'autre', 'autres',
  'fait', 'faire', 'été', 'peut', 'fera', 'font', 'faut', 'doit',
  'sera', 'seront', 'était', 'étaient', 'ont', 'avait',
  'tous', 'toute', 'toutes', 'aucun', 'aucune', 'tant', 'peu', 'trop',
  'encore', 'déjà', 'alors', 'ainsi', 'jamais', 'toujours',
  'souvent', 'parfois', 'seulement', 'vraiment', 'environ',
  'où', 'quand', 'comment', 'pourquoi', 'combien',
  'celui', 'cela', 'ceci', 'lequel', 'laquelle', 'lesquels', 'lesquelles',
  'oui', 'non', 'si',
  'peut', 'doit', 'veut', 'sait', 'voit',
  'jour', 'jours', 'fois', 'temps', 'ans', 'année', 'années',
  'bon', 'bonne', 'grand', 'grande', 'petit', 'petite',
  'premier', 'première', 'nouveau', 'nouvelle', 'nouveaux', 'nouvelles',
  'propre', 'propres', 'véritable', 'forte', 'fortes',
  'vie', 'monde', 'façon', 'manière', 'part', 'place',
  // English
  'the', 'and', 'for', 'with', 'from', 'this', 'that', 'are', 'was', 'will', 'been',
  'not', 'but', 'all', 'can', 'has', 'her', 'his', 'its', 'may', 'our', 'she',
  'they', 'them', 'their', 'what', 'which', 'who', 'whom', 'how', 'when', 'where',
  'would', 'could', 'should', 'have', 'had', 'does', 'did', 'being', 'having',
  'each', 'every', 'both', 'few', 'more', 'most', 'other', 'some', 'such',
  'into', 'over', 'after', 'before', 'between', 'through', 'about',
  'than', 'then', 'just', 'also', 'very', 'often', 'here', 'there',
  'your', 'you', 'we', 'my', 'me', 'him',
]);
